### ISSUE TITLE
Ajouter les utilitaires et serveurs geo

### ISSUE THREAD

**Issue by mborne** [mborne/mborne.github.io#9]
```yaml
- name: ogr2ogr
  description: Utilitaire de transformation de format de données
  tags:
    - GIS
    - IO
    - Vector
    - Raster
    - Projection
  url: http://www.gdal.org/ogr2ogr.html

- name: osm2pgsql
  description: Utilitaire de chargement des données OSM dans PostgreSQL
  tags:
    - IO
    - Vector
    - OSM
  url: https://github.com/openstreetmap/osm2pgsql#osm2pgsql

- name: mapshaper
  description: Utilitaire de manipulation des données offrant entre autre des
    fonctionnalités de simplification géométrique conservant la topologie à
    l'échelle d'une couche.
  tags:
    - GIS
    - IO
    - Vector
    - Simplify
    - Clip
    - Dissolve
  url: https://github.com/mbloch/mapshaper#mapshaper

- name: grass
  description: Ensemble d'utilitaires de traitement de données spatiales image et vecteur
  tags:
    - GIS
    - Geometry
    - Image
    - PointCloud
  url: https://grass.osgeo.org/documentation/general-overview/

- name: mapserver
  description: Application pour la mise en ligne de données géographiques (WFS, WMS)
  tags:
    - Map
    - WFS
    - WMS
  url: http://mapserver.org/

- name: geoserver
  description: Application pour la mise en ligne de données géographiques (WFS, WMS, WMTS)
  tags:
    - Map
    - WFS
    - WMS
    - WMTS
  url: http://geoserver.org

- name: geonetwork
  description: Catalogage des données géographiques (CSW, CSW-T)
  tags:
    - CSW
    - CSW-T
    - metadata
  url: https://www.geonetwork-opensource.org/

```
